### ISSUE TITLE
iOS: lost breadcrumb in remarks tab

### ISSUE THREAD

**Issue by difiore** [ethoinformatics/ethoinfo-project-app#28] opened 2016-05-25 18:28 UTC
- pulling up keyboard in remarks tab shifts screen upwards to where breadcrumb is no longer seen; also, text size in remarks tab very small

**Comment by tigoe** [comment] 2016-07-15 19:48
7/15/16: @jcousins @relevante, change font size in remarks, slightly larger.  

@difiore keyboard sliding the breadcrumb aside is a feature, not a bug. It's built into os'es. Closing the keyboard returns it.

**Comment by jcousins** [comment] 2016-07-25 12:57
Changed font size in remarks to something slightly larger, about 15%. I also slightly bumped up the leading (vertical spacing between lines). Together these go a long way to aid usability here. Tested using lengthy “Lorem ipsum…” passage.

**Closed as completed by jcousins** 2016-07-25 12:57 UTC

**Comment by tigoe** [comment] 2016-07-28 20:13
better, though I'll defer to @difiore and @kchiou. Being farsighted, my guess is another 5-10% woudn't hurt
